language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -e .
  - pip install -e '.[test]'
# command to run tests
script:
  - coverage run -m pytest
  - coverage report